### ISSUE TITLE
Should arg (.withArgs) handle description?

### ISSUE THREAD

**Issue by Paradoxia** [pgutkowski/KGraphQL#1]
I'm wondering if `arg` should also handle "description" when doing introspection. Currently i can only set/get "name" and "defaultValue".

Btw. After experimenting with multiple graphql frameworks (spent a week) i finally came to the conclusion that your library is the best one for Kotlin developers like me. I'm very grateful for your work.

**Comment by pgutkowski** [comment]
`arg` definitely should handle description. I've done quick investigation and found cause of this bug, it will be fixed soon.

Thank you very much for your feedback and kind words! I'm really happy that you have found this library useful.

**Comment by Paradoxia** [comment]
After some more debugging I noticed that "deprecate" becomes the description.

`   .withArgs {
                        arg<Int> {
                            name = "page"
                            defaultValue = 0
                            deprecate("becomes description")
                        }
                    }`

**Comment by pgutkowski** [comment]
That's true, I've messed up order of constructor arguments in DSL consumer, my bad, should have used explicit argument names.

**Comment by pgutkowski** [comment]
@Paradoxia issue has been fixed and merged to master. It will come out with next release in coming days. Thank you for your report!

**Comment by Paradoxia** [comment]
@pgutkowski Awesome thank you. I found a similar problem on **property**

```
type<Production> {
    property<String?>("country") {
        description = "Country description"
        resolver { production -> production.country }
    }
}


{
  __type(name: "Production") {
    name
    description
    fields {
      name
      description
      type {
        name
        description
        kind
        ofType {
          name
          description
          kind
        }
      }
    }
  }
}


---> Slice from result -->

{
  "name": "country",
  "description": null, <---- MISSING
  "type": {
    "name": "String",
    "description": "The String scalar type represents textual data, represented as UTF‐8 character sequences",
    "kind": "SCALAR",
    "ofType": null
  }
}

```
The query doesn't output the description i created for property "country".

**Comment by pgutkowski** [comment]
I see, it seems I have to thoroughly check whether DSL descriptions are properly passed to schema. I am sorry for your problems with it, I hope I will be able to fix it tomorrow and release new version.

Again, thank you for your feedback and reports!

**Comment by pgutkowski** [comment]
It seems that you are doing the same thing as in https://github.com/pgutkowski/KGraphQL/issues/4, where `property<>` invocation ads new property which duplicates existing kotlin property. 

Please try to add description with 
```kotlin
type<Production> {
    property(Production::country) {
        description = "Country description"
    }
}
```
and see if description is missing.

**Comment by Paradoxia** [comment]
You are completely right. Code now works as expected. Handing out this :1st_place_medal: to you for your excellent library and support.

**Comment by pgutkowski** [comment]
Thanks! Always happy to help :smile:
