### ISSUE TITLE
dsl?

### ISSUE THREAD

**Issue by larsespen9** [pgutkowski/KGraphQL#18]
What is dsl?
It provides rich DSL to setup GraphQL schema ...

**Comment by pgutkowski** [comment]
Hi @larsespen9, DSL is abbreviation for **D**omain **S**pecific **L**anguage, please see: https://en.wikipedia.org/wiki/Domain-specific_language, or more Kotlin-specific source: https://kotlinlang.org/docs/reference/type-safe-builders.html
