### ISSUE TITLE
Merging schemas would be helpful 

### ISSUE THREAD

**Issue by Paradoxia** [pgutkowski/KGraphQL#2]
I'm currently working on wrapping multiple rest- and microservices into a single graphql schema. The only problem I have is that my single schema becomes very bloated and large. It would be very helpful if it was possible to merge multiple schemas into one single schema.

Again thank you very much for your awesome framework :)

**Comment by pgutkowski** [comment]
I see your point. It is not straightforward, but it is possible to merge multiple schema declarations. Function `KGraphQL.schema` accepts instance of receiver function `SchemaBuilder.() -> Unit`, but you can compose them, example:
```kotlin
    val schemaPartOne : SchemaBuilder.() -> Unit = {
        query("hello") {
            resolver { name : String -> "Hello, $name" }
        }
    }

    val schemaPartTwo : SchemaBuilder.() -> Unit = {
        query("goodbye") {
            resolver { name : String -> "Goodbye, $name" }
        }
    }

    val schema = KGraphQL.schema {
        schemaPartOne()
        schemaPartTwo()
    }
```
This mechanism has been used in [KGraphQL demo application](https://github.com/pgutkowski/KGraphQL-NBA2012), see [ApiConfiguration.kt](https://github.com/pgutkowski/KGraphQL-NBA2012/blob/master/src/main/kotlin/com/github/pgutkowski/kgraphqlnba/ApiConfiguration.kt)

Anyway, this is not as simple as it should and I guess we need some better solution. This issue will stay open as long as some satisfying solution will come up.

Thank you for your great feedback!

**Comment by Paradoxia** [comment]
Great this work as well. No need for merge. Just a small note. After implementing your suggested pattern I noticed that I had to pass "this" to the SchemaBuilders.

```
  val schema = KGraphQL.schema {
        schemaPartOne(this)
        schemaPartTwo(this)
    }
```

**Comment by pgutkowski** [comment]
Oh, I've thought that compiler will be able to infer receiver. Thank you for pointing that out. I will extend wiki with article about modular schema creation, based on you question.

Thanks!
