### ISSUE TITLE
Usage with Dataloaders?

### ISSUE THREAD

**Issue by Togrias** [pgutkowski/KGraphQL#20]
Is there any way I can make this work with dataloaders i.e. the one that comes default with graphql java or node dataloader js libs?

**Comment by pgutkowski** [comment]
Hi @Togrias,

You can put in resolver function anything that returns instance of declared object, so based on [this example](https://github.com/graphql-java/java-dataloader#examples) from `java-dataloader` it would look like:
```kotlin
        query("user") {
            resolver{ id: Long -> 
                userLoader.load(id).dispatchAndJoin()
            }
        }
```

of course you have to initialize loader first, as shown in example.
