### ISSUE TITLE
Create a branch with suspend resolvers support

### ISSUE THREAD

**Issue by Bertrand** [pgutkowski/KGraphQL#22]
Currently, KGraphQL does not support suspend resolvers.

Adding support to current master is hard (if even possible) because kotlin 1.2 (current stable version) doesn't support reflection on suspend functions. 

Support for this has been added in kotlin 1.3-M2, and it would be nice to have an 'async' branch with support for suspend resolvers, until kotlin 1.3 is out. 

Proposed implementation available in PR #21

**Comment by pgutkowski** [comment]
Hi @Bertrand,

Thank you for your contribution, I will review the PR later today.

**Comment by pgutkowski** [comment]
@Bertrand,

Thank you very much for your contribution, great job! Thank you for upgrading some dependencies too. I've merged your branch to branch `0.3.0-alpha` and released package with pre-release version `0.3.0-alpha`. When Kotlin 1.3 will be released, I will release main version 0.3.0 with your changes.
