### ISSUE TITLE
Quotes within argument string not supported

### ISSUE THREAD

**Issue by deepakyadav** [pgutkowski/KGraphQL#24]
If value for a parameter contains escaped quoted, then the query fails because of failure in parsing the request. The error varies depending on what follows the quoted value, I think quotes are not handled properly:
https://github.com/pgutkowski/KGraphQL/blob/master/src/main/kotlin/com/github/pgutkowski/kgraphql/request/RequestPreProcessing.kt#L24

Example:
```
{
     hello(name : "Ted\" Mosby")
}
```

However, passing such strings using query variables works perfectly fine.

**Comment by pgutkowski** [comment]
Hi @deepakyadav!

Thank you for reporting this issue, issue has been fixed in new version 0.2.8.
