### ISSUE TITLE
Line Graph

### ISSUE THREAD

**Issue by joshvapeter** [pgutkowski/KGraphQL#28]
Hello,
    Below is my JSON output. Can I plot line graph using KGraphQL? If your response is YES then what are all the libraries that I need to include in my project.

  private var jsonStringArray = "[{\"dailyrate\":\"2018-09-01\",\"usercount\":33},{\"dailyrate\":\"2018-09-02\",\"usercount\":44},{\"dailyrate\":\"2018-09-03\",\"usercount\":23},{\"dailyrate\":\"2018-09-04\",\"usercount\":77}] "

**Comment by pgutkowski** [comment]
Hi, 

Unfortunately, as README states, KGraphQL is Kotlin implementation of [GraphQL](https://graphql.org/), API query language, not plotting library. You should check out libraries like https://github.com/holgerbrandl/kravis.
