### ISSUE TITLE
release for stable coroutine support

### ISSUE THREAD

**Issue by NikkyAI** [pgutkowski/KGraphQL#30]
At the moment no version of kgraphql works with non-experimental coroutines
as of now i am unable to update to ktor 1.0.0-beta-1

with `0.3.0-alpha`
it does not compile:
```
Class 'com.github.pgutkowski.kgraphql.schema.Schema' is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
```

with `0.2.8` it breaks at runtime 
`kotlinx/coroutines/experimental/CommonPool` does not exist

i will attempt to make a PR

**Comment by pgutkowski** [comment]
Thank you for your PR @NikkyAI, I've released new version 0.3.0-beta with your contribution and fixes from master branch.
