### ISSUE TITLE
There is no instruction to help a new user to start the server and the client in this example. How can I run the server and start query? 

### ISSUE THREAD

**Issue by nguyenedward** [pgutkowski/KGraphQL#39]

**Comment by jeggy** [comment]
I've made a very simple example, including a react project here: https://github.com/jeggy/ktorgraphql

I could work a bit more on it and provide instructions on how to start it up. But for now it should be simple enough.

**Comment by nguyenedward** [comment]
Thanks
Nguyen Viet Trung 

   On Friday, November 30, 2018, 7:19:43 PM CST, Jógvan Olsen <notifications@github.com> wrote: 
 
 
I've made a very simple example, including a react project here: https://github.com/jeggy/ktorgraphql

I could work a bit more on it and provide instructions on how to start it up. But for now it should be simple enough.
