### ISSUE TITLE
property<> require a resolver

### ISSUE THREAD

**Issue by Paradoxia** [pgutkowski/KGraphQL#4]
I'm trying give a property a description like this
```
        type<Image> {
            property<Int>("width") {
                description = "Width of image in pixels"
            }
        }
```
but get a ```lateinit property functionWrapper has not been initialized``` exception.

The only way I get around the problem is to add a simple resolver like this
```
        type<Image> {
            property<Int>("width") {
                description = "Width of image in pixels"
                resolver { it -> it.width }
            }
        }
```

Am I doing anything wrong? Is there an easier way to give a property a description?

**Comment by pgutkowski** [comment]
See wiki article: https://github.com/pgutkowski/KGraphQL/wiki/Kotlin-Properties.

It should look like that:
```kotlin
type<Image> {
    property(Image::width){
        description = "Width of image in pixels"
    }
}
```

Method `property` with String as first argument extends Kotlin type with additional property. passing existing Kotlin property to it allows you to describe and depreciate existing properties of Kotlin types. 

It seems that wiki entry for properties should be more clear in that matter, so no following users won't have the same problem.

**Comment by Paradoxia** [comment]
My bad sorry, your right. I missed that out in the wiki. Now I get my code to work as expected :+1: 
Thank you for your time and patience.
