### ISSUE TITLE
Fragment ...InputValue does not exist

### ISSUE THREAD

**Issue by Paradoxia** [pgutkowski/KGraphQL#5]
I'm trying to create some documentation by using tools available on the internet. Tried both [graphdoc](https://github.com/2fd/graphdoc) and [graphql-docs](https://www.npmjs.com/package/graphql-docs). Unfortunately both of them fail because of the exception ```Fragment ...InputValue} does not exist```.

Here are the queries that the tools use.

```
query IntrospectionQuery {
    __schema {
        queryType {
            name
        }
        mutationType {
            name
        }
        subscriptionType {
            name
        }
        types {
            ...FullType
        }
        directives {
            name
            description
            args {
                ...InputValue
            }
            onOperation
            onFragment
            onField
        }
    }
}

fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
        name
        description
        args {
            ...InputValue
        }
        type {
            ...TypeRef
        }
        isDeprecated
        deprecationReason
    }
    inputFields {
        ...InputValue
    }
    interfaces {
        ...TypeRef
    }
    enumValues(includeDeprecated: true) {
        name
        description
        isDeprecated
        deprecationReason
    }
    possibleTypes {
        ...TypeRef
    }
}

fragment InputValue on __InputValue {
    name
    description
    type {
        ...TypeRef
    }
    defaultValue
}

fragment TypeRef on __Type {
    kind
    name
    ofType {
        kind
        name
        ofType {
            kind
            name
            ofType {
                kind
                name
            }
        }
    }
}
```

```
query IntrospectionQuery {
    __schema {
        queryType { name description kind}
        mutationType { name description kind }
        subscriptionType { name description kind }
        types {
            name
            kind
            description
            ...FullType
        }
        directives {
            name
            description
            locations
            args {
                ...InputValue
            }
        }
    }
}


fragment FullType on __Type {
    fields(includeDeprecated: true) {
        name
        description
        args {
            ...InputValue
        }
        type {
            ...TypeRef
        }
        isDeprecated
        deprecationReason
    }
    inputFields {
        ...InputValue
    }
    interfaces {
        ...TypeRef
    }
    enumValues(includeDeprecated: true) {
        name
        description
        isDeprecated
        deprecationReason
    }
    possibleTypes {
        ...TypeRef
    }
}

fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
}

fragment TypeRef on __Type {
    kind
    name
    description
    ofType {
        kind
        name
        description
        ofType {
            kind
            name
            description
            ofType {
                kind
                name
                description
                ofType {
                    kind
                    name
                    description
                    ofType {
                        kind
                        name
                        description
                        ofType {
                            kind
                            name
                            description
                            ofType {
                                kind
                                name
                                description
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by pgutkowski** [comment]
There is an issue with nested fragments : right now fragments are resolved sequentially, so if query would define `InputValue` fragment and then `FullType`, it would work, but not other way around. I was aware of it but I didn't have time to do it yet. It will get on top of my priorities. Thank you very much for your report.

BTW First query is weird, it has selection set
```
        directives {
            name
            description
            args {
                ...InputValue
            }
            onOperation
            onFragment
            onField
        }
```
GraphQL spec does not define `onOperation`, `onFragment` or `onField` for `__Directive` type, see http://facebook.github.io/graphql/#sec-The-__Directive-Type. Second query seems to be perfectly valid.

**Comment by Paradoxia** [comment]
Maybe ```onOperation```, ```onFragment``` and ```onField``` belongs to an upcoming specification or a draft? Noticed some frameworks implementing them.

[graphql-java](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/GraphQLDirective.java)

[graphql.v0](https://godoc.org/gopkg.in/chris-ramon/graphql.v0)

**Comment by pgutkowski** [comment]
Hm, maybe. Or it was part of previous versions of spec. Anyway, I have fixed nested fragments issue and released 0.2.1 version. It contains fix for #1 too. Please try it and close this issue if effects will be satisfying.

Thank you for your input and issue reports, it is really valuable for development of this library!

**Comment by Paradoxia** [comment]
Okay so ```graphdoc``` can now execute the introspection query and create documentation. But there is something strange going on. I noticed that my query doesn't show up in the documentation. This is how it looks in my code.

```
  query("productions") {
            description = "Get list of productions"
            resolver { page: Int -> streamlyResolver.listProductions(page) }
                    .withArgs {
                        arg<Int> {
                            name = "page"
                            defaultValue = 0
                            description = "Page number (starting from 0)"
                        }
                    }
        }
```
If i do my own introspection query like this
```
{
  __schema {
    queryType {
      name
      fields {
        name
        description
        args {
          name
          description
          type { name description }
        }
      }
    }
  }
}

----> result --->

{
  "data": {
    "__schema": {
      "queryType": {
        "name": "Query",
        "fields": [
          {
            "name": "productions",
            "description": "Get list of productions",
            "args": [
              {
                "name": "page",
                "description": "Page number (starting from 0)",
                "type": {
                  "name": null,
                  "description": "NonNull wrapper type"
                }
              }
            ]
          } ...
```
then i can see my query. BUT neither ```graphdoc``` or ```graphql-docs``` use that kind of query to extract available queries from the schema. Instead I think they expect queries to show up in this.
```
                    types {
                        name
                        kind
                        description
                        ...FullType
                    }
```

**Comment by Paradoxia** [comment]
Someone created this mega introspection [query](https://gist.github.com/craigbeck/b90915d49fda19d5b2b17ead14dcd6da#file-introspection-query-graphql-L6) that you could try out (- onOperation,onFragment and onField). Looks like it also expect queries to show up under "types".

**Comment by pgutkowski** [comment]
Okay, I will take a look on that. I'm starting to think that adding `onOperation`, `onFragment` and `onField` fields to `__Directive` for compatibility purposes would be good idea too.

**Comment by Paradoxia** [comment]
Good idea. I suggest you add ```onOperation, onFragment, onField``` but as deprecated fields. If I understand it right they have been replaced by ```locations``` (under directives)

**Comment by pgutkowski** [comment]
`0.2.3` version has been released, it was tested with `graphql-docs` and `graph-doc` and now it works just fine with creation of static documentation. `onOperation, `onFragment`, `onField` fields has been added to `__Directive`. 

Please check if it works for you. Have in mind that `graphql-docs` seems to not support union types: https://github.com/mhallin/graphql-docs/blob/master/src/model.js#L3

**Comment by Paradoxia** [comment]
I'm getting expected result. Good job.
