### ISSUE TITLE
KProperty.ignore() should cascade to subclasses

### ISSUE THREAD

**Issue by joscha-alisch** [pgutkowski/KGraphQL#7]
Let's say I have two classes, one being a subclass of the other. The parent class has a property that I want to be ignored in GraphQL. I currently have to use KProperty.ignore() on both types.

```
open class A (val title: String)
class B(title: String) : A(title)

val schema = schema {
    type<A> {
        A::title.ignore() // This does not apply to B
    }
    
    type<B> {
        B::title.ignore() // I have to explicitly ignore it here too
    }
}
```

I feel like using ignore() in a type should cascade down to all subtypes. In this specific case it's not a big deal ignoring the property on both types. But in bigger content-models, this quickly becomes tedious, if the property to ignore is high up in the hierarchy.

**Comment by pgutkowski** [comment]
Hi @joscha-alisch, I'm sorry for late reply. I think you have a point, I will check how we can easily introduce this improvement.

Thanks!

**Comment by pgutkowski** [comment]
Hey @joscha-alisch, this issue has been fixed, after next release, ignored properties will cascade.

Thank you for your contribution!
