### ISSUE TITLE
Possibility to define custom scalar types

### ISSUE THREAD

**Issue by joscha-alisch** [pgutkowski/KGraphQL#8]
Other GraphQL libraries allow the definition of custom scalar types.

http://dev.apollodata.com/tools/graphql-tools/scalars.html#Date-as-a-scalar as an example.

It would be awesome to get this feature also for KGraphQL!

**Comment by pgutkowski** [comment]
KGraphQL already has this feature, see [wiki](https://github.com/pgutkowski/KGraphQL/wiki/Scalars). Please let me know if this satisfies you.

**Comment by pgutkowski** [comment]
Since there is no response, I am closing this issue.
